# Generated by Django 3.0.2 on 2020-04-08 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20200328_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendence',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='admission_no',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='taken_on',
            field=models.DateField(),
        ),
    ]
