# Generated by Django 3.0.3 on 2020-04-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20200408_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
