# Generated by Django 3.0.2 on 2020-04-26 07:05

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20200413_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='hour',
            field=django_mysql.models.EnumField(choices=[('HOUR_1', '1st Hour'), ('HOUR_2', '2nd Hour'), ('HOUR_3', '2rd Hour'), ('HOUR_4', '4th Hour'), ('HOUR_5', '5th Hour'), ('HOUR_6', '6th Hour')], default='HOUR_1'),
            preserve_default=False,
        ),
    ]
