# Generated by Django 3.0.3 on 2020-07-20 10:59

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_attendence_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='hour',
            field=django_mysql.models.EnumField(choices=[('HOUR_1', '1st Hour'), ('HOUR_2', '2nd Hour'), ('HOUR_3', '2rd Hour'), ('HOUR_4', '4th Hour'), ('HOUR_5', '5th Hour'), ('HOUR_6', '6th Hour')], default='HOUR_1'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 16, 29, 40, 761833)),
        ),
    ]
